/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AdminNoPermissionRouteImport } from './routes/admin.no-permission'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppTransactionsRouteImport } from './routes/_authenticated/app.transactions'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppHomeRouteImport } from './routes/_authenticated/app.home'
import { Route as AuthenticatedAppBenefitsRouteImport } from './routes/_authenticated/app.benefits'
import { Route as AuthenticatedAdminTransactionsRouteImport } from './routes/_authenticated/admin.transactions'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminIntegrationsRouteImport } from './routes/_authenticated/admin.integrations'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin.events'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminTransactionsManualRouteImport } from './routes/_authenticated/admin.transactions.manual'
import { Route as AuthenticatedAdminSettingsBrandRouteImport } from './routes/_authenticated/admin.settings.brand'
import { Route as AuthenticatedAdminSettingsAuditLogsRouteImport } from './routes/_authenticated/admin.settings.audit-logs'
import { Route as AuthenticatedAdminSettingsAdminsRouteImport } from './routes/_authenticated/admin.settings.admins'
import { Route as AuthenticatedAdminPoliciesTiersRouteImport } from './routes/_authenticated/admin.policies.tiers'
import { Route as AuthenticatedAdminPoliciesProductsRouteImport } from './routes/_authenticated/admin.policies.products'
import { Route as AuthenticatedAdminPoliciesBaseRouteImport } from './routes/_authenticated/admin.policies.base'
import { Route as AuthenticatedAdminCustomersIdRouteImport } from './routes/_authenticated/admin.customers.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminNoPermissionRoute = AdminNoPermissionRouteImport.update({
  id: '/admin/no-permission',
  path: '/admin/no-permission',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppTransactionsRoute =
  AuthenticatedAppTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppHomeRoute = AuthenticatedAppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBenefitsRoute =
  AuthenticatedAppBenefitsRouteImport.update({
    id: '/benefits',
    path: '/benefits',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAdminTransactionsRoute =
  AuthenticatedAdminTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIntegrationsRoute =
  AuthenticatedAdminIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTransactionsManualRoute =
  AuthenticatedAdminTransactionsManualRouteImport.update({
    id: '/manual',
    path: '/manual',
    getParentRoute: () => AuthenticatedAdminTransactionsRoute,
  } as any)
const AuthenticatedAdminSettingsBrandRoute =
  AuthenticatedAdminSettingsBrandRouteImport.update({
    id: '/settings/brand',
    path: '/settings/brand',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsAuditLogsRoute =
  AuthenticatedAdminSettingsAuditLogsRouteImport.update({
    id: '/settings/audit-logs',
    path: '/settings/audit-logs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsAdminsRoute =
  AuthenticatedAdminSettingsAdminsRouteImport.update({
    id: '/settings/admins',
    path: '/settings/admins',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPoliciesTiersRoute =
  AuthenticatedAdminPoliciesTiersRouteImport.update({
    id: '/policies/tiers',
    path: '/policies/tiers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPoliciesProductsRoute =
  AuthenticatedAdminPoliciesProductsRouteImport.update({
    id: '/policies/products',
    path: '/policies/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPoliciesBaseRoute =
  AuthenticatedAdminPoliciesBaseRouteImport.update({
    id: '/policies/base',
    path: '/policies/base',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersIdRoute =
  AuthenticatedAdminCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminCustomersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/no-permission': typeof AdminNoPermissionRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRouteWithChildren
  '/app/benefits': typeof AuthenticatedAppBenefitsRoute
  '/app/home': typeof AuthenticatedAppHomeRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/transactions': typeof AuthenticatedAppTransactionsRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/policies/base': typeof AuthenticatedAdminPoliciesBaseRoute
  '/admin/policies/products': typeof AuthenticatedAdminPoliciesProductsRoute
  '/admin/policies/tiers': typeof AuthenticatedAdminPoliciesTiersRoute
  '/admin/settings/admins': typeof AuthenticatedAdminSettingsAdminsRoute
  '/admin/settings/audit-logs': typeof AuthenticatedAdminSettingsAuditLogsRoute
  '/admin/settings/brand': typeof AuthenticatedAdminSettingsBrandRoute
  '/admin/transactions/manual': typeof AuthenticatedAdminTransactionsManualRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/no-permission': typeof AdminNoPermissionRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRouteWithChildren
  '/app/benefits': typeof AuthenticatedAppBenefitsRoute
  '/app/home': typeof AuthenticatedAppHomeRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/transactions': typeof AuthenticatedAppTransactionsRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/policies/base': typeof AuthenticatedAdminPoliciesBaseRoute
  '/admin/policies/products': typeof AuthenticatedAdminPoliciesProductsRoute
  '/admin/policies/tiers': typeof AuthenticatedAdminPoliciesTiersRoute
  '/admin/settings/admins': typeof AuthenticatedAdminSettingsAdminsRoute
  '/admin/settings/audit-logs': typeof AuthenticatedAdminSettingsAuditLogsRoute
  '/admin/settings/brand': typeof AuthenticatedAdminSettingsBrandRoute
  '/admin/transactions/manual': typeof AuthenticatedAdminTransactionsManualRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/no-permission': typeof AdminNoPermissionRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/transactions': typeof AuthenticatedAdminTransactionsRouteWithChildren
  '/_authenticated/app/benefits': typeof AuthenticatedAppBenefitsRoute
  '/_authenticated/app/home': typeof AuthenticatedAppHomeRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/transactions': typeof AuthenticatedAppTransactionsRoute
  '/_authenticated/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/_authenticated/admin/policies/base': typeof AuthenticatedAdminPoliciesBaseRoute
  '/_authenticated/admin/policies/products': typeof AuthenticatedAdminPoliciesProductsRoute
  '/_authenticated/admin/policies/tiers': typeof AuthenticatedAdminPoliciesTiersRoute
  '/_authenticated/admin/settings/admins': typeof AuthenticatedAdminSettingsAdminsRoute
  '/_authenticated/admin/settings/audit-logs': typeof AuthenticatedAdminSettingsAuditLogsRoute
  '/_authenticated/admin/settings/brand': typeof AuthenticatedAdminSettingsBrandRoute
  '/_authenticated/admin/transactions/manual': typeof AuthenticatedAdminTransactionsManualRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/app'
    | '/admin/login'
    | '/admin/no-permission'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/integrations'
    | '/admin/reports'
    | '/admin/transactions'
    | '/app/benefits'
    | '/app/home'
    | '/app/profile'
    | '/app/transactions'
    | '/admin/customers/$id'
    | '/admin/policies/base'
    | '/admin/policies/products'
    | '/admin/policies/tiers'
    | '/admin/settings/admins'
    | '/admin/settings/audit-logs'
    | '/admin/settings/brand'
    | '/admin/transactions/manual'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin'
    | '/app'
    | '/admin/login'
    | '/admin/no-permission'
    | '/'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/integrations'
    | '/admin/reports'
    | '/admin/transactions'
    | '/app/benefits'
    | '/app/home'
    | '/app/profile'
    | '/app/transactions'
    | '/admin/customers/$id'
    | '/admin/policies/base'
    | '/admin/policies/products'
    | '/admin/policies/tiers'
    | '/admin/settings/admins'
    | '/admin/settings/audit-logs'
    | '/admin/settings/brand'
    | '/admin/transactions/manual'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/admin/login'
    | '/admin/no-permission'
    | '/_authenticated/'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/integrations'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/transactions'
    | '/_authenticated/app/benefits'
    | '/_authenticated/app/home'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/transactions'
    | '/_authenticated/admin/customers/$id'
    | '/_authenticated/admin/policies/base'
    | '/_authenticated/admin/policies/products'
    | '/_authenticated/admin/policies/tiers'
    | '/_authenticated/admin/settings/admins'
    | '/_authenticated/admin/settings/audit-logs'
    | '/_authenticated/admin/settings/brand'
    | '/_authenticated/admin/transactions/manual'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNoPermissionRoute: typeof AdminNoPermissionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/no-permission': {
      id: '/admin/no-permission'
      path: '/admin/no-permission'
      fullPath: '/admin/no-permission'
      preLoaderRoute: typeof AdminNoPermissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/transactions': {
      id: '/_authenticated/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AuthenticatedAppTransactionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/home': {
      id: '/_authenticated/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AuthenticatedAppHomeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/benefits': {
      id: '/_authenticated/app/benefits'
      path: '/benefits'
      fullPath: '/app/benefits'
      preLoaderRoute: typeof AuthenticatedAppBenefitsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/transactions': {
      id: '/_authenticated/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AuthenticatedAdminTransactionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/integrations': {
      id: '/_authenticated/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AuthenticatedAdminIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/transactions/manual': {
      id: '/_authenticated/admin/transactions/manual'
      path: '/manual'
      fullPath: '/admin/transactions/manual'
      preLoaderRoute: typeof AuthenticatedAdminTransactionsManualRouteImport
      parentRoute: typeof AuthenticatedAdminTransactionsRoute
    }
    '/_authenticated/admin/settings/brand': {
      id: '/_authenticated/admin/settings/brand'
      path: '/settings/brand'
      fullPath: '/admin/settings/brand'
      preLoaderRoute: typeof AuthenticatedAdminSettingsBrandRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings/audit-logs': {
      id: '/_authenticated/admin/settings/audit-logs'
      path: '/settings/audit-logs'
      fullPath: '/admin/settings/audit-logs'
      preLoaderRoute: typeof AuthenticatedAdminSettingsAuditLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings/admins': {
      id: '/_authenticated/admin/settings/admins'
      path: '/settings/admins'
      fullPath: '/admin/settings/admins'
      preLoaderRoute: typeof AuthenticatedAdminSettingsAdminsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/policies/tiers': {
      id: '/_authenticated/admin/policies/tiers'
      path: '/policies/tiers'
      fullPath: '/admin/policies/tiers'
      preLoaderRoute: typeof AuthenticatedAdminPoliciesTiersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/policies/products': {
      id: '/_authenticated/admin/policies/products'
      path: '/policies/products'
      fullPath: '/admin/policies/products'
      preLoaderRoute: typeof AuthenticatedAdminPoliciesProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/policies/base': {
      id: '/_authenticated/admin/policies/base'
      path: '/policies/base'
      fullPath: '/admin/policies/base'
      preLoaderRoute: typeof AuthenticatedAdminPoliciesBaseRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers/$id': {
      id: '/_authenticated/admin/customers/$id'
      path: '/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AuthenticatedAdminCustomersIdRouteImport
      parentRoute: typeof AuthenticatedAdminCustomersRoute
    }
  }
}

interface AuthenticatedAdminCustomersRouteChildren {
  AuthenticatedAdminCustomersIdRoute: typeof AuthenticatedAdminCustomersIdRoute
}

const AuthenticatedAdminCustomersRouteChildren: AuthenticatedAdminCustomersRouteChildren =
  {
    AuthenticatedAdminCustomersIdRoute: AuthenticatedAdminCustomersIdRoute,
  }

const AuthenticatedAdminCustomersRouteWithChildren =
  AuthenticatedAdminCustomersRoute._addFileChildren(
    AuthenticatedAdminCustomersRouteChildren,
  )

interface AuthenticatedAdminTransactionsRouteChildren {
  AuthenticatedAdminTransactionsManualRoute: typeof AuthenticatedAdminTransactionsManualRoute
}

const AuthenticatedAdminTransactionsRouteChildren: AuthenticatedAdminTransactionsRouteChildren =
  {
    AuthenticatedAdminTransactionsManualRoute:
      AuthenticatedAdminTransactionsManualRoute,
  }

const AuthenticatedAdminTransactionsRouteWithChildren =
  AuthenticatedAdminTransactionsRoute._addFileChildren(
    AuthenticatedAdminTransactionsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRouteWithChildren
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminIntegrationsRoute: typeof AuthenticatedAdminIntegrationsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminTransactionsRoute: typeof AuthenticatedAdminTransactionsRouteWithChildren
  AuthenticatedAdminPoliciesBaseRoute: typeof AuthenticatedAdminPoliciesBaseRoute
  AuthenticatedAdminPoliciesProductsRoute: typeof AuthenticatedAdminPoliciesProductsRoute
  AuthenticatedAdminPoliciesTiersRoute: typeof AuthenticatedAdminPoliciesTiersRoute
  AuthenticatedAdminSettingsAdminsRoute: typeof AuthenticatedAdminSettingsAdminsRoute
  AuthenticatedAdminSettingsAuditLogsRoute: typeof AuthenticatedAdminSettingsAuditLogsRoute
  AuthenticatedAdminSettingsBrandRoute: typeof AuthenticatedAdminSettingsBrandRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCustomersRoute:
    AuthenticatedAdminCustomersRouteWithChildren,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
  AuthenticatedAdminIntegrationsRoute: AuthenticatedAdminIntegrationsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminTransactionsRoute:
    AuthenticatedAdminTransactionsRouteWithChildren,
  AuthenticatedAdminPoliciesBaseRoute: AuthenticatedAdminPoliciesBaseRoute,
  AuthenticatedAdminPoliciesProductsRoute:
    AuthenticatedAdminPoliciesProductsRoute,
  AuthenticatedAdminPoliciesTiersRoute: AuthenticatedAdminPoliciesTiersRoute,
  AuthenticatedAdminSettingsAdminsRoute: AuthenticatedAdminSettingsAdminsRoute,
  AuthenticatedAdminSettingsAuditLogsRoute:
    AuthenticatedAdminSettingsAuditLogsRoute,
  AuthenticatedAdminSettingsBrandRoute: AuthenticatedAdminSettingsBrandRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppBenefitsRoute: typeof AuthenticatedAppBenefitsRoute
  AuthenticatedAppHomeRoute: typeof AuthenticatedAppHomeRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppTransactionsRoute: typeof AuthenticatedAppTransactionsRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppBenefitsRoute: AuthenticatedAppBenefitsRoute,
  AuthenticatedAppHomeRoute: AuthenticatedAppHomeRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppTransactionsRoute: AuthenticatedAppTransactionsRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNoPermissionRoute: AdminNoPermissionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
